### PR TITLE
Refactor main file

### PR DESCRIPTION
**Pull request by paleloser**
Key points addressed as part of this PR:

* Isolated CSP client configuration and implementation into `src/client/csp.ts`
* Isolated VIB client configuration and implementation into `src/client/vib.ts`
* Distributed the constants declared in `constants.ts` to the files where they are actually needed
* Updated tests and tests boundaries accordingly (CSP tests have been moved to `csp.test.ts`
* Moved util functions (used in multiple files) `getNumberInput` and `getNumberArray` to `src/util.ts`
* Moved configuration handling to `src/config.ts`

Having this differentiation makes easier to read the action code, to know where each logical part may be located, and to test each component individually as well as in conjunction by allowing to mock each part more granurally.

Some aspects that aren't covered by this PR:

* No new tests are added: the goal of this PR is to move code between files keeping the current tests and functionality.
* Following a testing structure convention: not every test follows a structural convention. Only those that needed refactoring were adapted to a given/when/then structure.
* Removing dependencies between tests: some tests depend on others (i.e. most of the tests in `main.test.ts` depend on the execution of the first one), we should isolate each test to make them easier to maintain and validate. This may be done by mocking external services or not, depending on the use case.

### CODE REVIEW

**Review by gdelgadot — APPROVED** [review]

**Comment by mpermar** [comment]
@paleloser great work here!

Before merging this, can you perhaps run a few tests with your own repository and point it to this branch? There are too many changes so having some actual real-life end to end test will help here.

**Comment by mpermar** [comment]
One difference I notice is this:

» Pipeline is still in progress, will check again in 30s.
  Warning: report.pipe is not a function
  Warning: report.pipe is not a function
  Warning: report.pipe is not a function
  Warning: report.pipe is not a function

**Comment by paleloser** [comment]
There you go, here's a passing one with the reports working https://github.com/paleloser/vmware-image-builder-action/actions/runs/3884821295/jobs/6627887502 I was passing the `responseType` through the headers instead of an `axios` parameter 🤦🏼

**Review by mpermar — APPROVED** [review]

**Comment by paleloser** [comment]
This execution proves that `VIB_ENV_TARGET_PLATFORM` is substituted, and that `SHA_ARCHIVE` is replaced by the URL pointing to the contents provided by GitHub. It is expected to fail because the `resources.path` does not exist in my fork https://github.com/paleloser/vmware-image-builder-action/actions/runs/3885302027/jobs/6629006964

**Pull request merged**
